use_dark_theme = true

[[sources]]
name = 'echo_cancel_source'
label = 'Echo Cancelled Mic'
hidden = false

[[sources]]
name = 'mic_and_stream_sink.monitor'
label = 'Mic + Stream'
hidden = false

[[sources]]
name = 'stream_sink.monitor'
label = 'Stream'
hidden = true

[[sources]]
name = 'alsa_input.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo'
label = '''I'm Fulla Schiit Digital Stereo (IEC958)'''
hidden = true

[[sources]]
name = 'alsa_output.pci-0000_0c_00.1.hdmi-stereo-extra2.monitor'
label = 'Monitor of Navi 21/23 HDMI/DP Audio Controller Digital Stereo (HDMI 3)'
hidden = true

[[sources]]
name = 'alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo.monitor'
label = '''Monitor of I'm Fulla Schiit Digital Stereo (IEC958)'''
hidden = true

[[sources]]
name = 'alsa_input.pci-0000_00_1f.3.analog-stereo'
label = 'Built-in Audio Analog Stereo'
hidden = true

[[sources]]
name = 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
label = 'Monitor of Built-in Audio Analog Stereo'
hidden = true

[[sources]]
name = 'stream_sink.echo-cancel.monitor'
label = '''Monitor of My Stream (echo cancelled with I'm Fulla Schiit Digital Stereo (IEC958))'''
hidden = true

[[sinks]]
name = 'alsa_output.pci-0000_0c_00.1.hdmi-stereo-extra2'
label = 'Speakers'
hidden = false

[[sinks]]
name = 'alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.iec958-stereo'
label = 'Headphones'
hidden = false

[[sinks]]
name = 'alsa_output.pci-0000_00_1f.3.analog-stereo'
label = 'Laptop Audio'
hidden = false

[[sinks]]
name = 'mic_and_stream_sink'
label = 'Mic + Stream'
hidden = true

[[sinks]]
name = 'stream_sink'
label = 'My Stream'
hidden = true

[[sinks]]
name = 'stream_sink.echo-cancel'
label = '''My Stream (echo cancelled with I'm Fulla Schiit Digital Stereo (IEC958))'''
hidden = true
